spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.mongodb.autoconfigure.MongoAutoConfiguration
      - org.springframework.boot.mongodb.autoconfigure.MongoReactiveAutoConfiguration
      - org.springframework.boot.mongodb.autoconfigure.health.MongoHealthContributorAutoConfiguration
      - org.springframework.boot.mongodb.autoconfigure.health.MongoReactiveHealthContributorAutoConfiguration
      - org.springframework.boot.mongodb.autoconfigure.metrics.MongoMetricsAutoConfiguration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stayops}
    username: ${SPRING_DATASOURCE_USERNAME:stayops}
    password: ${SPRING_DATASOURCE_PASSWORD:stayops}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jooq:
    sql-dialect: POSTGRES
