spring:
  application:
    name: stayops
  profiles:
    active: local
  session:
    redis:
      repository-type: default
    timeout: 30m

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

toss:
  payments:
    secret-key: test_sk_AQ92ymxN34gLqb4q69np8ajRKXvd
    base-url: ${TOSS_BASE_URL:https://api.tosspayments.com/v1/payments}

mock-ota:
  endpoint: ${MOCK_OTA_ENDPOINT:http://localhost:8081}
