name: stayops-mongo

services:
  mongo:
    image: mongo:8
    command: ["mongod", "--replSet", "${MONGO_REPLICA_SET:-rs0}", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - stayops-mongo

  mongodb-exporter:
    image: percona/mongodb_exporter:0.43.1
    command:
      - "--mongodb.uri=mongodb://mongo:27017/admin"
      - "--collect-all"
    ports:
      - "9216:9216"
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - stayops-mongo

  node-exporter:
    image: prom/node-exporter:latest
    command:
      - "--path.rootfs=/host"
    pid: host
    volumes:
      - "/:/host:ro,rslave"
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - stayops-mongo

  promtail:
    image: grafana/promtail:latest
    command: ["-config.file=/etc/promtail/config.yml", "-config.expand-env=true"]
    environment:
      LOKI_URL: ${LOKI_URL}
      HOSTNAME: ${HOSTNAME}
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail.yml:/etc/promtail/config.yml:ro
    restart: unless-stopped
    networks:
      - stayops-mongo

volumes:
  mongo_data:

networks:
  stayops-mongo:
    driver: bridge
